### ISSUE TITLE
Problems running the scritp

### ISSUE THREAD

**Issue by noeliaprimor** [jangaraj/zenoss5-core-autodeploy#1]
We need to add the interface name and the hostname to run the script. If the inteface name is not eth0 it doesnt run.

Thank you!!

**Comment by jangaraj** [comment]
Thank you for your feedback.

1.) IP problem
```
echo -e "${yellow}2.1 IP configurations${endColor}"
# ifconfig is not available in min installation - ip addr show used
privateipv4=$(ip addr show | grep -A 1 'eth0' | grep inet | awk '{print $2}' | awk -F'/' '{print $1}')
privateipv42=$(ip addr show | grep -A 1 'eno' | grep inet | awk '{print $2}' | awk -F'/' '{print $1}')
# test of empty - ask input from user
if [ -z "$privateipv4" ] && [ -z "$privateipv42" ]; then
    echo "Network interface auto detection failed. Available interfaces in your system:"
    ls /sys/class/net | grep -v lo
    echo "Please write interface, which you want to use for deployement, e.g. eth1 or ens160:"
    read interface
    privateipv4=$(ip addr show | grep -A 1 $interface | grep inet | awk '{print $2}' | awk -F'/' '{print $1}')
fi
```
It will ask user input, when eth0, or some eno interface is not presented with IP in the system. List of available interfaces is provided. In your case, please write ens160.

2.) first serviced start failed
```
echo -e "${yellow}4.1 Adding current host to the default resource pool${endColor}"
echo -e "${yellow}Please be patient, because docker image zenoss/serviced-isvcs must be downloaded before first start${endColor}"
echo -e "${yellow}Script is trying to check status every 10s. Time limit is 15 minutes.${endColor}"
```
Image download took 12 minutes on my home network, so I've increased timeout to 15 minutes and I've added note to the script. Old timeout was only 2 minutes, which is fine for enterprise production network, but not for home users.

Could please test 2015-03-12 version and could you provide your feedback again.

Thx

**Comment by jepke** [comment]
guess im running into something similar my interface is ens160 so i chose that one but now im stuck on 4.1 i tried to rerun the script with eth1 without luck.

Error:
#17: Control Service is not fully started, I'm trying in next 10 seconds
could not create a client to the master: dial tcp 10.1.1.50:4979: connection refused

Don't know where to start looking for this

**Comment by frankyjoa** [comment]
jepke, let it run and be patient. Same situation for me, ens160 and the Control Service is not fu.... error message comes back several times until it's all ready. On my ESX system, it has to go to #37.... and it went through fine.

**Comment by jangaraj** [comment]
I agree. First start of serviced (Control Center) can take ages if you are using slow home network = ~12minutes in my case (= retry #72). Check 
```
journalctl -u systemd -f
```
If it's there ~"downloading image ...", keep calm and be patient :-) serviced is working and it's downloading docker images.

**Comment by jepke** [comment]
went thru twice the entire 15 minute loop (second time eth1)

Im also on ESX guess it is downloading something in the background but im on 1:1 50Mbit fiber

**Comment by jangaraj** [comment]
@jepke Could you post your full output (pastebin.com) from auto-deploy script + output from "journalctl -u systemd -f" please. Thx.

**Comment by jepke** [comment]
output of journalctl =

-- Logs begin at Tue 2015-03-17 09:27:02 CET. --
thats it

**Comment by jepke** [comment]
might the amount of RAM be the problem? i only assigned 10G to my virtual machine. Because i don't have more on my test host.

**Comment by jangaraj** [comment]
IMHO RAM is not bottleneck in this step. It can be problem only when you start all Zenoss.core containers/services.
Could you post your full output (pastebin.com) from auto-deploy script + output from "journalctl -u systemd -f" please. Thx.

**Comment by jepke** [comment]
just did all output in here http://pastebin.com/LnsRTPd0 or do you need more?

**Comment by jangaraj** [comment]
```
Network interface auto detection failed. Available interfaces in your system:
docker0
ens32
Please write interface, which you want to use for deployement, e.g. eth1 or ens160:
ens160
```
Name convention of interfaces has been changed in RHEL 7 - you have available only:
docker0
ens32
No eth1/ens160 (they are only examples in the script). Please use ens32 in your case and probably build from the scratch will be best for you.

**Comment by jepke** [comment]
shame on me again reading carefully was the solution :) ill give it a try if things are broken further down the trail ill build from scratch

**Comment by jangaraj** [comment]
2.1 improved, user input is required only when user has more than 1 "real" network interface in the system. For selected interface is also IPv4 empty test there. It should eliminate jepke behaviour :-)
```
echo -e "${yellow}2.1 IP configurations${endColor}"
# ifconfig is not available in min installation - ip addr show used
is=$(ls /sys/class/net | grep -v ^lo | grep -v ^docker0 | grep -v ^veth)
no=$(echo ${is} | tr ' ' "\n" | wc -l)
if [ "$no" -gt "1" ]; then
    echo "Network interface auto detection failed. Available interfaces in your system:"
    echo $is
    echo "Please write interface, which you want to use for deployement (see listing above), e.g. eth1 or ens160:"
    read interface
    privateipv4=$(ip addr show | grep -A 1 $interface | grep inet | awk '{print $2}' | awk -F'/' '{print $1}')
    if [ -z "$privateipv4" ]; then
        echo -e "${red}IPv4 address for selected interface ${interface} was not detected.${endColor}"
        exit 1
    fi
else
    echo "Detected interface: ${is}"
    privateipv4=$(ip addr show | grep -A 1 $is | grep inet | awk '{print $2}' | awk -F'/' '{print $1}')
fi  
```
