### ISSUE TITLE
CentOS 7 VM on Hyper-V 2012 R2 host shows 1GB less ram than allocated to VM

### ISSUE THREAD

**Issue by claflico** [jangaraj/zenoss5-core-autodeploy#2]
Realize the documentation says 20GB min but experimenting with less ram since we have a small environment. When I had 4GB on the VM it said that only 3GB was detected, now with an 8GB VM it says 7GB.

"Only 7 GB of RAM has been detected, but at least 20GB is recommended. Do you want to continue (y/N)?"

             total       used       free     shared    buffers     cached
Mem:       8005600     254424    7751176       8512       1840      85872
-/+ buffers/cache:     166712    7838888
Swap:      4194300          0    4194300

**Comment by jangaraj** [comment]
```
free -g
```
is used for detection of GB of memory. Actually 8005600k = 7.634735107421875G. It depends on the *free* command how is it rounded. I don't see any issue, because user has still option to say Yes (y) - I would like to continue, although I don't have recommended 20G of memory.

**Comment by claflico** [comment]
I still see it as being presented incorrectly to the end user (I work with alot of users who are new to Linux and who get confused by messages like this). You could make the message more user-friendly by changing it to say "Only X GB of free RAM has been detected"

**Comment by jangaraj** [comment]
I don't agree.
```
man free
```
DESCRIPTION
       free  displays the total amount of free and used physical and swap mem‐
       ory in the system, as well as the buffers and caches used by  the  ker‐
       nel.  The  information  is  gathered by parsing /proc/meminfo. The dis‐
       played columns are:

       total  Total installed memory (MemTotal and SwapTotal in /proc/meminfo)

*Total* memory value is used in my script, not *Free*. They are two different metrics.
