### ISSUE TITLE
CentOS 7 VM on Windows 2012 R2 Hyper-V host with necessary 30GB VHd reports volumes too small

### ISSUE THREAD

**Issue by claflico** [jangaraj/zenoss5-core-autodeploy#3]
The documentation says that min 30GB & 1GB volumes are necessary:

These filesystems must be mounted with correct type and size:
Filesystem                  Type        Min size
/                           xfs         30GB
/var/lib/docker             btrfs       30GB
/opt/serviced/var           xfs         30GB
/opt/serviced/var/volumes   btrfs       1GB
/opt/serviced/var/backups   btrfs               1GB

So I create 30GB VHDs and add them to the VM and created partitions on them:

fdisk -l

Disk /dev/sdc: 4294 MB, 4294967296 bytes, 8388608 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x1be4f69e

   Device Boot      Start         End      Blocks   Id  System
/dev/sdc1            2048     4196351     2097152   83  Linux
/dev/sdc2         4196352     8388607     2096128   83  Linux

Disk /dev/sda: 42.9 GB, 42949672960 bytes, 83886080 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000a7913

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048     1026047      512000   83  Linux
/dev/sda2         1026048    83886079    41430016   8e  Linux LVM

Disk /dev/sdd: 32.2 GB, 32212254720 bytes, 62914560 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0xd8abc9d5

   Device Boot      Start         End      Blocks   Id  System
/dev/sdd1            2048    62914559    31456256   83  Linux

Disk /dev/sdb: 32.2 GB, 32212254720 bytes, 62914560 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0xcfb0814d

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1            2048    62914559    31456256   83  Linux

Disk /dev/mapper/centos_zenoss-root: 38.1 GB, 38126223360 bytes, 74465280 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/centos_zenoss-swap: 4294 MB, 4294967296 bytes, 8388608 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

1 Checks - (Sat, 21 Mar 2015 19:30:44 -0500)
1.1 Root permission check
Done
1.2 Architecture check
Done
1.3 OS version check
Done
1.4 CPU check
Done
1.5 RAM check
Only 7 GB of RAM has been detected, but at least 20GB is recommended. Do you want to continue (y/N)?
y
 ... continuing
1.6 / filesystem check
Done
1.7 /var/lib/docker filesystem check
/var/lib/docker filesystem size is less than required 30GB

This was after I had installed CentOS on a 30GB VHD (with LVM) and then had to re-install the OS after expanding the VHD due to an error message that the root volume was too small.

Might update the documentation to state that 33-25GB is the min to account for the loss from partitioning.

**Comment by jangaraj** [comment]
```
Might update the documentation to state that 33-25GB is the min to account for the loss from partitioning.
``` 
It depends. Problem is that filesystem reserves some space for the root (usually 5%), so this file space is "visible" for the user. But documentation is saying about size of filesystem, not block device (VHD), so IMHO documentation is right :-)

If you want to update documentation, please raise ticket for Zenoss company. I'm not responsible for doc and I'm not Zenoss employer.
